### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arkusahu** [zyramedia/ng2-facebook-sdk-example#1]
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/@ngtools/webpack/src/index.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/models/webpack-build-typescript.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/commands/build.js:4:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/addon/index.js:21:16)
    at /Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/ember-cli/lib/models/project.js:335:61
    at Array.forEach (native)
    at Project.addonCommands (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/ember-cli/lib/models/project.js:334:15)
    at Project.eachAddonCommand (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/ember-cli/lib/models/project.js:369:30)
    at module.exports (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/angular-cli/ember-cli/lib/cli/cli.js:43:26)
    at tryCatch (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/arun.a.kumar.sahu/Desktop/ng2-facebook-sdk-example-master/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by arkusahu** [comment]
I did npm install
and then did npm start 
I got the above error
Please give working solution.

**Comment by ihadeed** [comment]
Sorry @arkusahu, I'm unable to reproduce those error messages.

What operating system are you working on? what node version?
